name: 'Add Directory'
description: 'Add a directory with specified name'
inputs:
  directoryName:
    description: 'Name of Directory'
    required: true
    default: 'ThisIsADirectory'
  fileName:
    description: 'File names'
    required: true
    default: 'default'
  fileContent:
    description: 'Content of the file'
    required: false
    default: 'Content'
outputs:
  time:
    description: 'Information'
    value: 'Made a directory called: ${{ inputs.directoryName }}'
runs:
  using: 'composite'
  steps:
  - run: ${{ github.action_path }}/test.sh
    shell: bash
    env:
      directoryName: ${{ inputs.directoryName }}
      fileName: ${{ inputs.fileName }}
      fileContent: ${{ inputs.fileContent }}